### ISSUE TITLE
Missing commands

### ISSUE THREAD

**Issue by YuGiOhJCJ** [rubenwardy/chatplus#10]
Hello,

In the last version of chatplus [1], I can see you forgot to register some commands:
```
$ grep -r "register_chatcommand"
init.lua:minetest.register_chatcommand("ignore", {
init.lua:minetest.register_chatcommand("unignore", {
```

Commands available:

- /ignore [name] - ignore a player
- /unignore [name] - unignore a player 

Commands not available:

- /mail [name] [msg] - message a player (online or offline!)
- /inbox - open your inbox
- /inbox clear - clear your inbox
- /inbox text - see the text version of the inbox.
- /inbox txt - alias of /inbox text
- /inbox t - alias of /inbox text

Have I misunderstood your code?

Thank you.
Best regards.

[1] 7c91e4cf0bc8828b7c07146d2655a90f320d5e11

Edit: Oh! That's not usual, the stable version is not in the "master" branch but in the "stable" branch.
So, I have not the last "stable" version but the last "unstable" version.
OK now with this last "stable" version it works :)

**Comment by rubenwardy** [comment]
Chatplus has split into two mods, chatplus and email: https://github.com/rubenwardy/email

**Comment by rubenwardy** [comment]
Email has /inbox /mail etc

**Comment by rubenwardy** [comment]
If you install the latest version of both, it will automatically migrate the data

**Comment by 0-afflatus** [comment]
Ah I just got bitten by that too - could you update README.md to include this information?

**Comment by rubenwardy** [comment]
Done https://github.com/rubenwardy/chatplus/commit/4777f3202fe68a6929598d4abf2d9a513a065e83
