### ISSUE TITLE
Integrate the new date format to the stable branch?

### ISSUE THREAD

**Issue by YuGiOhJCJ** [rubenwardy/chatplus#11]
Hello,

As the "master" branch is an unstable branch where a lot of commands are not yet available [1], can you integrate the new date format [2] to the "stable" branch too?

Thank you.
Best regards.

[1} https://github.com/rubenwardy/chatplus/issues/10
[2] 902edc122ab6e82db42e4f627b5136ba24150b6e

**Comment by rubenwardy** [comment]
Chatplus is a little bit outdated and needs some work from me to fix some things. I recommend you look into the [ignore](https://forum.minetest.net/viewtopic.php?t=13993) and [email](https://forum.minetest.net/viewtopic.php?t=13754) mods. Ignore works a lot better than chatplus, just looking at the code.
