### ISSUE TITLE
swearing filter

### ISSUE THREAD

**Issue by stormchaser3000** [rubenwardy/chatplus#7]
i know there is a swearing filter planned. but it would be nice. i have a skyblock server that i hardly ever modderate. and i would like to have a mod that is compatible with the irc mod that blocks swear words like fairiestoy's mod used to do

**Comment by stormchaser3000** [comment]
oh i just realized this was a duplicate.

**Comment by rubenwardy** [comment]
Already exists: https://github.com/rubenwardy/chatplus/blob/master/init.lua#L401

minetest.conf: chatplus_badword = one, two, threee

however it completely blocks the message rather than ****-ing.
