### ISSUE TITLE
Chat only relaying to IRC

### ISSUE THREAD

**Issue by DI3HARD139** [rubenwardy/chatplus#9]
I've been getting a few reports where players are not able to see what others are saying in chat unless they connect to IRC and read it there. There haven't been any crashes nor errors.

**Comment by rubenwardy** [comment]
using the latest version? Hmmm...

**Comment by DI3HARD139** [comment]
Yes its the latest version.

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/chatplus/commit/1b7cfeaab933b7676bbea6c40cbcedd3817fddd0
